from http import HTTPStatus


IMAGES = set('jpg jpe jpeg png gif svg bmp'.split())
MAX_CONTENT_LENGTH = 16 * 1024 * 1024
NULL = 0
ONE = 1
TWELVE = 12
FORBIDDEN = HTTPStatus.FORBIDDEN
INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
NOT_FOUND = HTTPStatus.NOT_FOUND
