"""new ralationship

Revision ID: 174faaf308af
Revises: 
Create Date: 2023-08-01 01:36:00.243044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174faaf308af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('added_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
