"""added relationship with User and Role

Revision ID: 388fdaf884a5
Revises: 777171753693
Create Date: 2023-08-06 19:41:44.787589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388fdaf884a5'
down_revision = '777171753693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    # ### end Alembic commands ###
