"""added models Role

Revision ID: 777171753693
Revises: 174faaf308af
Create Date: 2023-08-06 19:27:56.728352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "777171753693"
down_revision = "174faaf308af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("active")

    op.drop_table("roles")
    # ### end Alembic commands ###
