"""added field fs_uniquifier

Revision ID: e946e0a4e7da
Revises: 388fdaf884a5
Create Date: 2023-08-06 22:22:22.542312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e946e0a4e7da"
down_revision = "388fdaf884a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "uniquifier_constraint", sa.String(length=64), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("uniquifier_constraint")

    # ### end Alembic commands ###
